title: Tigunia Documentation Test
description: The first attempt at a better documentation site
theme: just-the-docs
layout: default

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

color_scheme: dark

callouts_level: quiet
callouts:
  warning:
    title: Warning
    color: red

url: https://tigunia.com

aux_links:
  Template Repository: https://github.com/tigunia-dave/learn-pages
